flathub/org.cryptomator.Cryptomator

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Wow, that took a while, it is very important to follow all steps mentioned in https://github.com/cryptomator/cryptomator/issues/729#issuecomment-1038752084 during the update.
> Update to 1.6.7

- org.cryptomator.Cryptomator.yaml
Like discussed [here](https://github.com/flathub/org.cryptomator.Cryptomator/issues/19).
> Add comments to explain finish-args

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Additionally, libfuse is updated to 3.14.0
> update to 1.7.2

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
For changes, see https://github.com/cryptomator/cryptomator/releases/tag/1.7.4
> Update to 1.7.4

- org.cryptomator.Cryptomator.yaml
> Updates Freedesktop Runtime to 22.08

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Updating maven, JDK and cryptomator
> Update to 1.9.3

- .gitignore
- .gitmodules
- org.cryptomator.Cryptomator.yaml
Add talk-name for appindicator
> Add monochrome icons for appindicator

- .gitignore
- .gitmodules
- maven-dependencies-aarch64.yaml
- maven-dependencies-x86_64.yaml
- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
> Release 1.10.0

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Changes:
* added JVM property `disableUpdateCheck` (see https://github.com/cryptomator/cryptomator/pull/3118)
* changed JVM property `cryptomator.showTrayIcon` to `true`
> Release 1.10.1

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Changes:
* Updated maven dependencies
* Updated JDK to 21.0.1+12
* Updated maven to 3.9.5
TODO:
> Release 1.11.0

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Release notes for app: https://github.com/cryptomator/cryptomator/releases/tag/1.11.1
> Release 1.11.1

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Changes:
* Updated to Cryptomator 1.12.3
* add comment for future automation (see #72)
For Cryptomator changelog, see  https://github.com/cryptomator/cryptomator/releases/tag/1.12.3
> Release: 1.12.3

- maven-dependencies-aarch64.yaml
- maven-dependencies-x86_64.yaml
- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Changes:
* Update JDK to 22.0.1+8
* Update JFX to 22.0.1+8
* Update maven dependencies
For app changes, see https://github.com/cryptomator/cryptomator/releases/tag/1.13.0-beta1.
> Release 1.13.0

- org.cryptomator.Cryptomator.yaml
References https://github.com/orgs/cryptomator/projects/9?pane=issue&itemId=57225865
> Remove deprecated jdk module

- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
> [!IMPORTANT]
> Todos:
> - [x] Update maven dependencies
> - [x] Check for JDK update
> - [x] Check for JFX update
> Release 1.14.2

- org.cryptomator.Cryptomator.yaml
Flag `enable-preview` was removed
> Update to jdk 23

- org.cryptomator.Cryptomator.yaml
See https://github.com/cryptomator/cryptomator/pull/3675
> read cert trust store from pkcs12 file in etc

- maven-dependencies-aarch64.yaml
- maven-dependencies-x86_64.yaml
- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Things added:
* Custom certificate file (#90)
* JDK 23 (#87)
* JFX 23
> 1.15.0 beta1

- maven-dependencies-aarch64.yaml
- maven-dependencies-x86_64.yaml
- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
> [!IMPORTANT]
> Todos:
> - [x] Update maven dependencies
> - [x] Check for JDK update
> - [x] Check for JFX update
> Release 1.15.0

- org.cryptomator.Cryptomator.yaml
> [!IMPORTANT]
> Todos:
> - [x] Update maven dependencies
> - [x] Check for JDK update
> - [x] Check for JFX update
> Release 1.15.1

- org.cryptomator.Cryptomator.yaml
> Add log dir

- maven-dependencies-aarch64.yaml
- maven-dependencies-x86_64.yaml
- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
Second attempt, pipeline seems to be stuck in #105
> Release 1.16.0

- maven-dependencies-aarch64.yaml
- maven-dependencies-x86_64.yaml
- maven-dependencies.yaml
- org.cryptomator.Cryptomator.yaml
> [!IMPORTANT]
> Todos:
> - [ ] Update maven dependencies
> - [ ] Check for JDK update
> - [ ] Check for JFX update
> Release 1.17.0
